import { sql } from "@/lib/db/neon";

const MIGRATION_VERSION = "004_killer_features";

const statements = [
  `CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY, email TEXT UNIQUE NOT NULL, name TEXT, image TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`,
  `CREATE TABLE IF NOT EXISTS chats (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, title TEXT NOT NULL DEFAULT 'New chat', created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`,
  `CREATE TABLE IF NOT EXISTS messages (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), chat_id UUID NOT NULL REFERENCES chats(id) ON DELETE CASCADE, role TEXT NOT NULL CHECK (role IN ('user','assistant')), content TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`,
  `CREATE TABLE IF NOT EXISTS email_connections (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, provider TEXT NOT NULL CHECK (provider IN ('google','microsoft')), provider_account_id TEXT, email TEXT NOT NULL, display_name TEXT, access_token TEXT NOT NULL, refresh_token TEXT, expires_at BIGINT, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), UNIQUE(user_id, provider, email))`,
  `CREATE TABLE IF NOT EXISTS campaigns (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, connection_id UUID NOT NULL REFERENCES email_connections(id) ON DELETE RESTRICT, name TEXT NOT NULL, subject TEXT NOT NULL, body TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','active','paused','completed')), start_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), interval_minutes INTEGER NOT NULL DEFAULT 60 CHECK (interval_minutes >= 1), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`,
  `CREATE TABLE IF NOT EXISTS email_approvals (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, connection_id UUID NOT NULL REFERENCES email_connections(id) ON DELETE CASCADE, campaign_id UUID REFERENCES campaigns(id) ON DELETE CASCADE, recipient TEXT NOT NULL, subject TEXT NOT NULL, body TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','approved','rejected','sending','sent','failed','send_unknown')), scheduled_at TIMESTAMPTZ, approved_at TIMESTAMPTZ, sent_at TIMESTAMPTZ, provider_message_id TEXT, error TEXT, send_attempts INTEGER NOT NULL DEFAULT 0, sending_started_at TIMESTAMPTZ, idempotency_key TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`,
  `CREATE TABLE IF NOT EXISTS rate_limit_buckets (key TEXT PRIMARY KEY, window_started_at TIMESTAMPTZ NOT NULL, count INTEGER NOT NULL DEFAULT 0, updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`,
  `CREATE TABLE IF NOT EXISTS research_runs (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, query TEXT NOT NULL, source TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'completed' CHECK (status IN ('running','completed','failed')), result_count INTEGER NOT NULL DEFAULT 0, metadata JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), completed_at TIMESTAMPTZ)`,
  `CREATE TABLE IF NOT EXISTS leads (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, name TEXT NOT NULL, email TEXT, website_url TEXT, website_verified BOOLEAN NOT NULL DEFAULT FALSE, website_status INTEGER, website_verified_at TIMESTAMPTZ, website_title TEXT, website_description TEXT, website_final_url TEXT, country TEXT, niche TEXT, youtube_channel_id TEXT, youtube_url TEXT, subscribers BIGINT, total_views BIGINT, contact_confidence NUMERIC(5,2) NOT NULL DEFAULT 0, lead_score NUMERIC(5,2) NOT NULL DEFAULT 0, score_reasons JSONB NOT NULL DEFAULT '[]'::jsonb, normalized_email TEXT, normalized_domain TEXT, normalized_youtube TEXT, first_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), last_researched_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`,
  `CREATE TABLE IF NOT EXISTS research_leads (research_run_id UUID NOT NULL REFERENCES research_runs(id) ON DELETE CASCADE, lead_id UUID NOT NULL REFERENCES leads(id) ON DELETE CASCADE, rank INTEGER, evidence JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), PRIMARY KEY (research_run_id, lead_id))`,
  `CREATE TABLE IF NOT EXISTS research_sources (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), research_run_id UUID NOT NULL REFERENCES research_runs(id) ON DELETE CASCADE, lead_id UUID REFERENCES leads(id) ON DELETE SET NULL, url TEXT NOT NULL, title TEXT, snippet TEXT, source_type TEXT NOT NULL DEFAULT 'web', fetched_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`,
  `CREATE TABLE IF NOT EXISTS campaign_steps (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), campaign_id UUID NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE, step_order INTEGER NOT NULL CHECK (step_order >= 1), delay_minutes INTEGER NOT NULL DEFAULT 0 CHECK (delay_minutes >= 0), subject TEXT NOT NULL, body TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), UNIQUE(campaign_id, step_order))`,
  `CREATE TABLE IF NOT EXISTS suppression_list (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, email TEXT NOT NULL, reason TEXT NOT NULL DEFAULT 'manual', source TEXT NOT NULL DEFAULT 'user', created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), UNIQUE(user_id, email))`,
  `CREATE TABLE IF NOT EXISTS email_events (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, campaign_id UUID REFERENCES campaigns(id) ON DELETE SET NULL, approval_id UUID REFERENCES email_approvals(id) ON DELETE SET NULL, recipient TEXT, event_type TEXT NOT NULL CHECK (event_type IN ('sent','delivered','opened','clicked','replied','bounced','failed','unsubscribed')), provider_message_id TEXT, provider_thread_id TEXT, metadata JSONB NOT NULL DEFAULT '{}'::jsonb, occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`,
  `CREATE TABLE IF NOT EXISTS campaign_contacts (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), campaign_id UUID NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE, lead_id UUID REFERENCES leads(id) ON DELETE SET NULL, recipient TEXT NOT NULL, current_step INTEGER NOT NULL DEFAULT 1, next_step_at TIMESTAMPTZ, state TEXT NOT NULL DEFAULT 'active' CHECK (state IN ('active','replied','bounced','suppressed','completed')), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), UNIQUE(campaign_id, recipient))`,
  `CREATE TABLE IF NOT EXISTS website_audits (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, lead_id UUID REFERENCES leads(id) ON DELETE CASCADE, url TEXT NOT NULL, score NUMERIC(5,2) NOT NULL DEFAULT 0, findings JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`,
  `CREATE TABLE IF NOT EXISTS demo_briefs (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, lead_id UUID REFERENCES leads(id) ON DELETE CASCADE, title TEXT NOT NULL, brief TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`,
  `CREATE TABLE IF NOT EXISTS lead_proposals (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, lead_id UUID REFERENCES leads(id) ON DELETE CASCADE, subject TEXT NOT NULL, body TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`,
  `CREATE TABLE IF NOT EXISTS lead_followups (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, lead_id UUID REFERENCES leads(id) ON DELETE CASCADE, step_order INTEGER NOT NULL, scheduled_at TIMESTAMPTZ NOT NULL, subject TEXT NOT NULL, body TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','scheduled','sent','cancelled')), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`,
  `CREATE TABLE IF NOT EXISTS crm_deals (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, lead_id UUID NOT NULL REFERENCES leads(id) ON DELETE CASCADE, stage TEXT NOT NULL DEFAULT 'new' CHECK (stage IN ('new','qualified','contacted','replied','meeting','proposal','won','lost')), notes TEXT NOT NULL DEFAULT '', next_action_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), UNIQUE(user_id, lead_id))`,
  `CREATE UNIQUE INDEX IF NOT EXISTS email_approvals_idempotency_idx ON email_approvals(idempotency_key) WHERE idempotency_key IS NOT NULL`,
  `CREATE INDEX IF NOT EXISTS email_events_campaign_idx ON email_events(campaign_id, occurred_at DESC)`,
  `CREATE INDEX IF NOT EXISTS email_events_recipient_idx ON email_events(user_id, recipient, occurred_at DESC)`,
  `CREATE INDEX IF NOT EXISTS campaign_contacts_due_idx ON campaign_contacts(campaign_id, state, next_step_at)`,
  `CREATE INDEX IF NOT EXISTS suppression_user_email_idx ON suppression_list(user_id, email)`,
  `CREATE INDEX IF NOT EXISTS website_audits_lead_idx ON website_audits(lead_id, created_at DESC)`,
  `CREATE INDEX IF NOT EXISTS demo_briefs_lead_idx ON demo_briefs(lead_id, created_at DESC)`,
  `CREATE INDEX IF NOT EXISTS lead_proposals_lead_idx ON lead_proposals(lead_id, created_at DESC)`,
  `CREATE INDEX IF NOT EXISTS lead_followups_due_idx ON lead_followups(user_id, status, scheduled_at)`,
  `CREATE INDEX IF NOT EXISTS crm_deals_stage_idx ON crm_deals(user_id, stage, updated_at DESC)`,
];

let migrationPromise: Promise<void> | null = null;

export function runProductionMigrations() {
  migrationPromise ??= (async () => {
    await sql`CREATE TABLE IF NOT EXISTS schema_migrations (version TEXT PRIMARY KEY, applied_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`;
    const existing = await sql`SELECT version FROM schema_migrations WHERE version=${MIGRATION_VERSION} LIMIT 1`;
    if (existing[0]) return;
    for (const statement of statements) await sql.unsafe(statement);
    await sql`INSERT INTO schema_migrations(version) VALUES (${MIGRATION_VERSION}) ON CONFLICT (version) DO NOTHING`;
  })().catch((error) => { migrationPromise = null; throw error; });
  return migrationPromise;
}
