import { NextResponse } from "next/server";
import { getRequestUser } from "@/lib/auth/request-user";
import { sql } from "@/lib/db/neon";
import { runProductionMigrations } from "@/lib/db/migrations";
import { generateAI } from "@/lib/intelligence/lead-intelligence";
import { AppError, errorResponse, errorStatus } from "@/lib/api/errors";
import { enforceRateLimit } from "@/lib/api/rate-limit";
import { z } from "zod";
const Body=z.object({offer:z.string().trim().min(1).max(5000),steps:z.number().int().min(1).max(5).default(3),startAt:z.string().datetime().optional()});
export async function GET(request:Request,{params}:{params:Promise<{id:string}>}){try{const user=await getRequestUser(request);await runProductionMigrations();const {id}=await params;const rows=await sql`SELECT * FROM lead_followups WHERE lead_id=${id} AND user_id=${user.uid} ORDER BY step_order`;return NextResponse.json({followups:rows});}catch(error){return NextResponse.json(errorResponse(error,"Unable to load follow-ups."),{status:errorStatus(error)});}}
export async function POST(request:Request,{params}:{params:Promise<{id:string}>}){try{const user=await getRequestUser(request);await runProductionMigrations();await enforceRateLimit(`lead:followups:${user.uid}`,20,60_000);const {id}=await params;const parsed=Body.safeParse(await request.json().catch(()=>null));if(!parsed.success)throw new AppError("VALIDATION_ERROR","Invalid follow-up request.",400);const lead=(await sql`SELECT * FROM leads WHERE id=${id} AND user_id=${user.uid} LIMIT 1`)[0] as any;if(!lead)throw new AppError("NOT_FOUND","Lead not found.",404);const prompt=`Write ${parsed.data.steps} short, respectful follow-up emails for a website-service prospect. Each must be distinct, low-pressure, and grounded in this lead and audit evidence. Return JSON array only with objects {subject,body}. Do not invent facts. Lead:${JSON.stringify({name:lead.name,niche:lead.niche,website:lead.website_url})}`;const text=await generateAI(prompt);let items:Array<{subject:string;body:string}>;try{items=JSON.parse(text)}catch{items=Array.from({length:parsed.data.steps},(_,i)=>({subject:`Following up — ${lead.name}`,body:text+(i?`\n\nFollow-up ${i+1}.`:"")}));}const start=parsed.data.startAt?new Date(parsed.data.startAt):new Date(Date.now()+3*24*60*60*1000);const saved=[];for(let i=0;i<Math.min(items.length,parsed.data.steps);i++){const item=items[i];const scheduled=new Date(start.getTime()+i*4*24*60*60*1000);const rows=await sql`INSERT INTO lead_followups(user_id,lead_id,step_order,scheduled_at,subject,body,status) VALUES(${user.uid},${id},${i+1},${scheduled.toISOString()},${item.subject||`Follow-up ${i+1}`},${item.body||""},'scheduled') RETURNING *`;saved.push(rows[0]);}return NextResponse.json({followups:saved},{status:201});}catch(error){return NextResponse.json(errorResponse(error,"Unable to generate follow-ups."),{status:errorStatus(error)});}}
