import { NextResponse } from "next/server";
import { getRequestUser } from "@/lib/auth/request-user";
import { sql } from "@/lib/db/neon";
import { runProductionMigrations } from "@/lib/db/migrations";
import { generateAI } from "@/lib/intelligence/lead-intelligence";
import { AppError, errorResponse, errorStatus } from "@/lib/api/errors";
import { enforceRateLimit } from "@/lib/api/rate-limit";
import { z } from "zod";
const Body=z.object({offer:z.string().trim().min(1).max(5000),senderName:z.string().trim().max(120).optional()});
export async function POST(request:Request,{params}:{params:Promise<{id:string}>}){try{const user=await getRequestUser(request);await runProductionMigrations();await enforceRateLimit(`lead:proposal:${user.uid}`,20,60_000);const {id}=await params;const parsed=Body.safeParse(await request.json().catch(()=>null));if(!parsed.success)throw new AppError("VALIDATION_ERROR","Offer is required.",400);const leadRows=await sql`SELECT * FROM leads WHERE id=${id} AND user_id=${user.uid} LIMIT 1`;const lead=leadRows[0] as any;if(!lead)throw new AppError("NOT_FOUND","Lead not found.",404);const auditRows=await sql`SELECT findings FROM website_audits WHERE lead_id=${id} AND user_id=${user.uid} ORDER BY created_at DESC LIMIT 1`;const audit=(auditRows[0] as any)?.findings||{};const prompt=`Create a concise personalized website proposal for this lead. Explain 2-3 specific website opportunities from the audit, then connect each opportunity to the offer. Return exactly:\nSubject: ...\n\nBody...\n\nLead: ${JSON.stringify({name:lead.name,email:lead.email,country:lead.country,niche:lead.niche,youtube_url:lead.youtube_url,subscribers:lead.subscribers,total_views:lead.total_views})}\nAudit: ${JSON.stringify(audit)}\nOffer: ${parsed.data.offer}\nSender: ${parsed.data.senderName||"Sanmine Space"}`;const text=await generateAI(prompt);const subject=text.match(/^Subject:\s*(.+)$/im)?.[1]?.trim()||`A website idea for ${lead.name}`;const body=text.replace(/^Subject:\s*.+\n?/im,"").trim();const saved=await sql`INSERT INTO lead_proposals(user_id,lead_id,subject,body) VALUES(${user.uid},${id},${subject},${body}) RETURNING *`;return NextResponse.json({proposal:saved[0]},{status:201});}catch(error){return NextResponse.json(errorResponse(error,"Unable to generate proposal."),{status:errorStatus(error)});}}
