import Link from "next/link";

export const metadata = { title: "Privacy Policy — Sanmine Space", description: "Privacy Policy for Sanmine Space." };

export default function PrivacyPage() {
  return (
    <main className="fixed inset-0 overflow-y-auto bg-[var(--bg)] px-6 py-10 text-[var(--text)] md:px-8">
      <article className="mx-auto max-w-3xl pb-16">
        <Link href="/" className="text-sm text-[var(--muted)] hover:text-[var(--text)]">← Sanmine Space</Link>
        <h1 className="mt-12 font-serif text-5xl tracking-[-0.04em]">Privacy Policy</h1>
        <p className="mt-4 text-sm text-[var(--muted)]">Last updated: September 2, 2026</p>
        <div className="mt-10 space-y-8 text-[15px] leading-7 text-[#4f4c45]">
          <section><h2 className="font-semibold text-[var(--text)]">1. Overview</h2><p className="mt-2">Sanmine Space is an AI workspace for research, lead discovery, analysis, proposals and outreach. This Privacy Policy explains what information we collect, why we use it, how we protect it, and the choices available to you.</p></section>
          <section><h2 className="font-semibold text-[var(--text)]">2. Information we collect</h2><p className="mt-2">When you sign in, we may receive your name, email address, profile image and a provider account identifier from Google Firebase Authentication. We store account information needed to provide your workspace and associate your chats with your account.</p><p className="mt-2">When you use Sanmine Space, we may store prompts, conversations, generated responses, research results, saved leads, proposal or email drafts, timestamps and related workspace metadata. We also receive technical information necessary to operate and secure the service, such as request logs and basic device or browser information.</p></section>
          <section><h2 className="font-semibold text-[var(--text)]">3. Google and Gmail data</h2><p className="mt-2">If you connect Gmail, Sanmine Space uses Google OAuth to request only the permissions needed for the Gmail features you choose to use. Depending on the enabled feature, this can include access needed to read relevant message information, create drafts, or send an email after an action is approved by you.</p><p className="mt-2">Gmail data is used only to provide the requested email integration and related features. We do not sell Gmail data, use it for advertising, or use it to build advertising profiles. We do not transfer Gmail data to unrelated third parties except where necessary to provide the requested service or comply with law.</p></section>
          <section><h2 className="font-semibold text-[var(--text)]">4. How we use information</h2><p className="mt-2">We use information to authenticate users, save and synchronize chats, operate AI features, perform requested web research, manage leads, generate proposals and email drafts, provide connected Gmail functionality, maintain security, troubleshoot failures, and improve reliability. We use your content to provide the features you explicitly request.</p></section>
          <section><h2 className="font-semibold text-[var(--text)]">5. AI processing</h2><p className="mt-2">Prompts and other content may be sent to the AI model providers configured by Sanmine Space so that the requested response can be generated. We send information necessary for the requested operation and do not sell your prompts or responses.</p></section>
          <section><h2 className="font-semibold text-[var(--text)]">6. Web research</h2><p className="mt-2">When you ask Sanmine Space to research the web, your request and relevant URLs may be processed by our research tools. Public web pages may be retrieved and summarized for you. Information found on public websites remains subject to those websites' own terms and privacy policies.</p></section>
          <section><h2 className="font-semibold text-[var(--text)]">7. Storage and security</h2><p className="mt-2">Account and workspace data is stored using service providers selected to operate Sanmine Space. Authentication is handled through Firebase Authentication. OAuth credentials and tokens are intended to be protected using server-side controls and encryption. We use reasonable technical and organizational safeguards, but no internet service can guarantee absolute security.</p></section>
          <section><h2 className="font-semibold text-[var(--text)]">8. Sharing</h2><p className="mt-2">We do not sell personal information. Information may be processed by infrastructure, authentication, database, AI, web-research and email service providers when required to deliver a feature you use. We may also disclose information when legally required, to protect users or the service, or to prevent abuse and security incidents.</p></section>
          <section><h2 className="font-semibold text-[var(--text)]">9. Retention and deletion</h2><p className="mt-2">We retain information for as long as needed to provide the service, maintain your workspace, satisfy legitimate operational needs, or comply with legal obligations. You may delete chats and disconnect connected services through available product controls. For account or data deletion requests that are not available in the product, contact us and we will review the request.</p></section>
          <section><h2 className="font-semibold text-[var(--text)]">10. Disconnecting Gmail</h2><p className="mt-2">You can disconnect Gmail from the Plugins area. Disconnecting stops Sanmine Space from using the connection for future Gmail operations. You can also revoke Sanmine Space's access from your Google Account security settings.</p></section>
          <section><h2 className="font-semibold text-[var(--text)]">11. Cookies and local storage</h2><p className="mt-2">Sanmine Space may use browser storage or similar technologies to keep the interface responsive, preserve local UI state and support authentication. These technologies are not used to sell personal information to advertisers.</p></section>
          <section><h2 className="font-semibold text-[var(--text)]">12. Children's privacy</h2><p className="mt-2">Sanmine Space is not intended for children who are not legally permitted to use the service. We do not knowingly collect personal information from children in violation of applicable law.</p></section>
          <section><h2 className="font-semibold text-[var(--text)]">13. Changes</h2><p className="mt-2">We may update this Privacy Policy when our service, integrations or legal requirements change. The updated version will be published on this page with a revised date.</p></section>
          <section><h2 className="font-semibold text-[var(--text)]">14. Contact</h2><p className="mt-2">Questions, privacy requests or concerns can be sent to <a className="underline" href="mailto:support.sanminespace@gmail.com">support.sanminespace@gmail.com</a>.</p></section>
        </div>
      </article>
    </main>
  );
}
