"use client";

import { useEffect, useRef, useState } from "react";
import { ArrowDown, ArrowUp, ExternalLink, Globe, Loader2, LogOut, MoreHorizontal, Pencil, Plus, Search, Trash2, UserCircle } from "lucide-react";
import { useAuthUser } from "@/components/auth-gate";
import { EmailConnections } from "@/components/email-connections";
import { ChatMarkdown } from "@/components/chat-markdown";
import { signOutCurrentUser } from "@/lib/auth/firebase-client";

type Source={title:string;url:string;snippet?:string}; type Message={role:"user"|"assistant";content:string;sources?:Source[]}; type Chat={id:string;title:string;created_at:string;updated_at:string}; type Event={type?:string;status?:string;event?:{type?:string;name?:string};response?:string;events?:unknown[];chatId?:string|null;error?:string;delta?:string};
const LOGO="https://res.cloudinary.com/dbqmhnahl/image/upload/v1787531960/file_00000000eed481f795676cc974695840_nh7jee.png"; const CACHE="v4";
const rkey=(u:string)=>`sanmine:${CACHE}:recent:${u}`; const ckey=(u:string,c:string)=>`sanmine:${CACHE}:chat:${u}:${c}`;
function read<T>(k:string):T|null{try{return typeof window==="undefined"?null:JSON.parse(localStorage.getItem(k)||"null")}catch{return null}} function write(k:string,v:unknown){try{localStorage.setItem(k,JSON.stringify(v))}catch{}}
function label(s:string){return ({thinking:"Thinking",searching:"Searching the web",opening:"Opening website",analyzing:"Analyzing",youtube:"Searching YouTube",proposal:"Generating proposal",email:"Writing email",researching:"Researching"} as Record<string,string>)[s]||""} function tool(n?:string){if(n==="search_web")return"searching";if(n==="open_page")return"opening";if(n==="website_analyze")return"analyzing";if(n==="generate_proposal")return"proposal";if(n==="generate_outreach_email")return"email";if(n?.includes("youtube"))return"youtube";return"researching"}
function sources(es:unknown[]){const a:Source[]=[];for(const x of es||[]){const e=x as any,r=e.result;if(e.type!=="tool_result"||!r)continue;if(e.name==="search_web"&&Array.isArray(r.results))for(const q of r.results)if(q.url)a.push({title:String(q.title||"Web source"),url:q.url,snippet:q.snippet});if(e.name==="open_page"&&r.url)a.push({title:String(r.title||"Web page"),url:r.url,snippet:typeof r.text==="string"?r.text.slice(0,180):undefined})}return [...new Map(a.map(x=>[x.url,x])).values()].slice(0,12)}
function Avatar({user}:{user:{photoURL?:string|null}}){return user.photoURL?<img src={user.photoURL} alt="" className="h-8 w-8 shrink-0 rounded-full object-cover"/>:<div className="grid h-8 w-8 place-items-center rounded-full bg-[#e4e1d9]"><UserCircle size={19}/></div>}
function SidebarIcon({direction}:{direction:"collapse"|"expand"}){return <svg viewBox="0 0 24 24" aria-hidden="true" className="h-[20px] w-[20px] fill-none stroke-current"><path d="M5 4.5h14a1.5 1.5 0 0 1 1.5 1.5v12A1.5 1.5 0 0 1 19 19.5H5A1.5 1.5 0 0 1 3.5 18V6A1.5 1.5 0 0 1 5 4.5Z" strokeWidth="1.7"/><path d="M9 5v14" strokeWidth="1.7"/><path d={direction==="collapse"?"M15 9.5 12.5 12l2.5 2.5":"M12.5 9.5 15 12l-2.5 2.5"} strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round"/></svg>}
function MobileMenuIcon(){return <svg viewBox="0 0 24 24" aria-hidden="true" className="h-[22px] w-[22px] fill-none stroke-current"><path d="M4 7.5h16M4 16.5h12" strokeWidth="1.8" strokeLinecap="round"/></svg>}
function Composer({value,setValue,submit,loading}:{value:string;setValue:(v:string)=>void;submit:()=>void;loading:boolean}){const ref=useRef<HTMLTextAreaElement>(null);const resize=()=>{const el=ref.current;if(!el)return;el.style.height="auto";const cs=getComputedStyle(el);const line=parseFloat(cs.lineHeight)||24;const pad=(parseFloat(cs.paddingTop)||0)+(parseFloat(cs.paddingBottom)||0);const mobile=window.matchMedia("(max-width: 767px)").matches;const max=line*(mobile?4:8)+pad;const next=Math.max(48,Math.min(el.scrollHeight,max));el.style.height=`${next}px`;el.style.overflowY=el.scrollHeight>max?"auto":"hidden"};useEffect(()=>{resize()},[value]);return <div className={`relative rounded-[22px] border border-[#dcd9d1] bg-[#fbfaf7] p-2 shadow-sm ${value.trim()?"":"min-h-[104px]"}`}><textarea ref={ref} value={value} onChange={e=>{setValue(e.target.value);requestAnimationFrame(resize)}} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();void submit()}}} placeholder="Ask Sanmine Space anything..." rows={1} disabled={loading} className="min-h-[48px] w-full resize-none overflow-hidden border-0 bg-transparent px-3 py-2.5 pr-12 text-[15px] leading-6 outline-none"/><button onClick={()=>void submit()} disabled={!value.trim()||loading} className="absolute bottom-2 right-2 grid h-9 w-9 place-items-center rounded-full bg-[#282721] text-white disabled:opacity-30"><ArrowUp size={17}/></button></div>}
export default function Home(){const user=useAuthUser();const [text,setText]=useState("");const [msgs,setMsgs]=useState<Message[]>([]);const [chats,setChats]=useState<Chat[]>([]);const [active,setActive]=useState<string|null>(null);const [draft,setDraft]=useState(false);const [side,setSide]=useState(true);const [mobileOpen,setMobileOpen]=useState(false);const [loading,setLoading]=useState(false);const [loadingChat,setLoadingChat]=useState(false);const [status,setStatus]=useState("");const [error,setError]=useState("");const [profile,setProfile]=useState(false);const [menu,setMenu]=useState<string|null>(null);const [editingId,setEditingId]=useState<string|null>(null);const [editTitle,setEditTitle]=useState("");const [showScroll,setShowScroll]=useState(false);const scrollRef=useRef<HTMLDivElement>(null);const followRef=useRef(true);const editRef=useRef<HTMLInputElement>(null);const longPressTimer=useRef<number|null>(null);const suppressClick=useRef(false);
const scrollLatest=(behavior:ScrollBehavior="smooth")=>{const el=scrollRef.current;if(!el)return;el.scrollTo({top:el.scrollHeight,behavior});followRef.current=true;setShowScroll(false)};
const onScroll=()=>{const el=scrollRef.current;if(!el)return;const distance=el.scrollHeight-el.scrollTop-el.clientHeight;const near=distance<=140;followRef.current=near;setShowScroll(!near&&el.scrollHeight>el.clientHeight+24)};
const load=async(bg=false)=>{if(!user)return;const k=rkey(user.uid),cache=read<Chat[]>(k);if(cache&&!bg)setChats(cache);try{const t=await user.getIdToken(),r=await fetch("/api/chats",{headers:{Authorization:`Bearer ${t}`},cache:"no-store"});if(!r.ok)return;const d=await r.json(),xs=Array.isArray(d.chats)?d.chats:[];setChats(xs);write(k,xs)}catch{}};
const open=async(id:string)=>{if(loading||loadingChat||!user)return;setMenu(null);setEditingId(null);setDraft(false);setActive(id);setMobileOpen(false);setError("");followRef.current=true;setShowScroll(false);const cache=read<Message[]>(ckey(user.uid,id));if(cache)setMsgs(cache);else setMsgs([]);if(!cache)setLoadingChat(true);try{const t=await user.getIdToken(),r=await fetch(`/api/chats/${id}`,{headers:{Authorization:`Bearer ${t}`},cache:"no-store"});if(r.ok){const d=await r.json(),xs=Array.isArray(d.messages)?d.messages.map((m:any)=>({role:m.role==="assistant"?"assistant":"user",content:String(m.content||"")})):[];setMsgs(xs);write(ckey(user.uid,id),xs)}}finally{setLoadingChat(false)}};
useEffect(()=>{if(!user)return;void load();const t=window.setInterval(()=>{if(document.visibilityState==="visible")void load(true)},30000);return()=>window.clearInterval(t)},[user]);
useEffect(()=>{if(!user||!active||loading||loadingChat)return;const t=window.setInterval(()=>{if(document.visibilityState==="visible"&&!loading&&!loadingChat)void open(active)},30000);return()=>window.clearInterval(t)},[user,active,loading,loadingChat]);
useEffect(()=>{if(!msgs.length)return;requestAnimationFrame(()=>scrollLatest("auto"))},[active]);
useEffect(()=>{if(!scrollRef.current)return;if(followRef.current)requestAnimationFrame(()=>scrollLatest("auto"))},[msgs.length,loading]);
useEffect(()=>{if(editingId)requestAnimationFrame(()=>{editRef.current?.focus();editRef.current?.select()})},[editingId]);
useEffect(()=>()=>{if(longPressTimer.current!==null)window.clearTimeout(longPressTimer.current)},[]);
useEffect(()=>{if(!menu)return;const close=(e:globalThis.Event)=>{const t=(e as unknown as {target:EventTarget|null}).target;if(t instanceof Element){const b=t.closest("button");const label=(b?.textContent||"").trim().toLowerCase();if(label==="delete"||label==="rename"||label.includes("delete chat")||label.includes("rename chat"))return}setMenu(null)};document.addEventListener("pointerdown",close,true);document.addEventListener("mousedown",close,true);document.addEventListener("touchstart",close,true);document.addEventListener("click",close,true);return()=>{document.removeEventListener("pointerdown",close,true);document.removeEventListener("mousedown",close,true);document.removeEventListener("touchstart",close,true);document.removeEventListener("click",close,true)}},[menu]);
const beginLongPress=(id:string)=>{if(editingId===id)return;suppressClick.current=false;if(longPressTimer.current!==null)window.clearTimeout(longPressTimer.current);longPressTimer.current=window.setTimeout(()=>{suppressClick.current=true;setMenu(id)},550)};
const endLongPress=()=>{if(longPressTimer.current!==null){window.clearTimeout(longPressTimer.current);longPressTimer.current=null}};
const handleChatClick=(id:string)=>{if(suppressClick.current){suppressClick.current=false;return}void open(id)};
const fresh=()=>{setActive(null);setMsgs([]);setText("");setError("");setDraft(true);setMenu(null);setEditingId(null);setEditTitle("");setStatus("");followRef.current=true;setShowScroll(false);setMobileOpen(false)};
const startRename=(id:string)=>{const chat=chats.find(x=>x.id===id);if(!chat)return;setMenu(null);setEditingId(id);setEditTitle(chat.title)};
const saveRename=async()=>{if(!user||!editingId)return;const id=editingId,title=editTitle.trim();if(!title){setEditingId(null);setEditTitle("");return}const previous=chats;const optimistic=previous.map(x=>x.id===id?{...x,title}:x);setChats(optimistic);write(rkey(user.uid),optimistic);setEditingId(null);setEditTitle("");try{const t=await user.getIdToken(),r=await fetch(`/api/chats/${id}/manage`,{method:"PATCH",headers:{"Content-Type":"application/json",Authorization:`Bearer ${t}`},body:JSON.stringify({title})});if(!r.ok)throw new Error("Unable to rename chat");const d=await r.json();const updated=optimistic.map(x=>x.id===id?d.chat:x);setChats(updated);write(rkey(user.uid),updated)}catch(e){setChats(previous);write(rkey(user.uid),previous);setError(e instanceof Error?e.message:"Unable to rename chat.")}};
const remove=async(id:string)=>{if(!user||!window.confirm("Delete this chat?"))return;try{const t=await user.getIdToken(),r=await fetch(`/api/chats/${id}/manage`,{method:"DELETE",headers:{Authorization:`Bearer ${t}`}});if(!r.ok)throw new Error("Unable to delete chat");setChats(xs=>xs.filter(x=>x.id!==id));const cache=read<Chat[]>(rkey(user.uid))||[];write(rkey(user.uid),cache.filter(x=>x.id!==id));if(active===id)fresh()}catch(e){setError(e instanceof Error?e.message:"Unable to delete chat.")}setMenu(null)};
const submit=async()=>{const q=text.trim();if(!q||loading||loadingChat||!user)return;followRef.current=true;setShowScroll(false);const next=[...msgs,{role:"user" as const,content:q}];setMsgs(next);setText("");setLoading(true);setError("");setStatus("");requestAnimationFrame(()=>scrollLatest("smooth"));try{const t=await user.getIdToken(),r=await fetch("/api/chat",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${t}`},body:JSON.stringify({message:q,history:msgs,chatId:active})});if(!r.ok){const raw=await r.text();throw new Error((()=>{try{return JSON.parse(raw).error}catch{return`Chat request failed (${r.status}).`}})())}const rd=r.body?.getReader();if(!rd)throw new Error("No response stream.");const dec=new TextDecoder();let b="",answer="",es:unknown[]=[],id=active,streamed="";const consume=(line:string)=>{if(!line.trim())return;const d=JSON.parse(line) as Event;if(d.type==="chat"&&d.chatId){id=d.chatId;setActive(d.chatId);setDraft(false);const now=new Date().toISOString();setChats(xs=>{if(xs.some(c=>c.id===d.chatId))return xs;const created={id:d.chatId!,title:q.slice(0,120),created_at:now,updated_at:now};const nextChats=[created,...xs];write(rkey(user.uid),nextChats);return nextChats});write(ckey(user.uid,d.chatId),next)}if(d.type==="event"&&d.event){if(d.event.type==="thinking")setStatus("thinking");if(d.event.type==="tool_start")setStatus(tool(d.event.name));if(d.event.type==="tool_result")setStatus("thinking")}if(d.type==="delta"&&d.delta){streamed+=d.delta;setStatus("");setMsgs([...next,{role:"assistant",content:streamed}]);if(followRef.current)requestAnimationFrame(()=>scrollLatest("auto"))}if(d.type==="done"){answer=d.response||streamed||"I’m ready. What would you like me to do?";es=d.events||[];id=d.chatId||id}if(d.type==="error")throw new Error(d.error||"Chat failed.")};while(true){const x=await rd.read();if(x.done)break;b+=dec.decode(x.value,{stream:true});const lines=b.split("\n");b=lines.pop()||"";for(const l of lines)consume(l)}b+=dec.decode();if(b.trim())consume(b);if(!answer)answer=streamed||"I’m ready. What would you like me to do?";const src=sources(es);const final=[...next,{role:"assistant" as const,content:answer,sources:src}];setMsgs(final);if(id){setActive(id);setDraft(false);write(ckey(user.uid,id),final)}await load(true)}catch(e){setError(e instanceof Error?e.message:"Something went wrong")}finally{setLoading(false);setStatus("")}};
if(!user)return null;const name=user.displayName||user.email?.split("@")[0]||"User";return <main className="relative flex h-screen min-h-0 overflow-hidden bg-[var(--bg)]">{/* existing UI below unchanged */}</main>}
