"use client";

import { useMemo, useState } from "react";

function Inline({text}:{text:string}){
  const parts=text.split(/(`[^`]+`|\*\*[^*]+\*\*|\[[^\]]+\]\([^\)]+\))/g);
  return <>{parts.map((p,i)=>{if(/^`[^`]+`$/.test(p))return <code key={i} className="rounded bg-black/[.06] px-1.5 py-0.5 font-mono text-[.9em]">{p.slice(1,-1)}</code>;if(/^\*\*[^*]+\*\*$/.test(p))return <strong key={i}>{p.slice(2,-2)}</strong>;const m=p.match(/^\[([^\]]+)\]\(([^\)]+)\)$/);if(m)return <a key={i} href={m[2]} target="_blank" rel="noreferrer" className="underline underline-offset-2">{m[1]}</a>;return <span key={i}>{p}</span>})}</>;
}
function Code({code,lang}:{code:string;lang?:string}){const [copied,setCopied]=useState(false);const copy=async()=>{try{await navigator.clipboard.writeText(code);setCopied(true);setTimeout(()=>setCopied(false),1400)}catch{}};return <div className="my-4 overflow-hidden rounded-xl border border-[#dedbd3] bg-[#1f1f1c] text-[#f4f1e9]"><div className="flex items-center justify-between border-b border-white/10 px-3 py-2 text-xs text-white/60"><span>{lang||"code"}</span><button onClick={copy} className="rounded-md px-2 py-1 text-white/80 hover:bg-white/10">{copied?"Copied":"Copy"}</button></div><pre className="overflow-x-auto p-4 text-[13px] leading-6"><code>{code}</code></pre></div>}
export function ChatMarkdown({content}:{content:string}){const blocks=useMemo(()=>content.split(/(```[\w-]*\n?[\s\S]*?```)/g),[content]);return <div className="space-y-3 text-[15px] leading-7">{blocks.map((block,i)=>{if(block.startsWith("```")){const m=block.match(/^```([\w-]*)\n?([\s\S]*?)```$/);return <Code key={i} lang={m?.[1]} code={(m?.[2]||block).replace(/\n$/,"")}/>;}const lines=block.split("\n");return <div key={i} className="space-y-2">{lines.map((line,j)=>{if(!line.trim())return <div key={j} className="h-1"/>;if(/^###\s+/.test(line))return <h3 key={j} className="pt-2 text-base font-semibold"><Inline text={line.replace(/^###\s+/,"")}/></h3>;if(/^##\s+/.test(line))return <h2 key={j} className="pt-2 text-lg font-semibold"><Inline text={line.replace(/^##\s+/,"")}/></h2>;if(/^#\s+/.test(line))return <h1 key={j} className="pt-2 text-xl font-semibold"><Inline text={line.replace(/^#\s+/,"")}/></h1>;if(/^[-*]\s+/.test(line))return <div key={j} className="flex gap-2 pl-1"><span>•</span><span><Inline text={line.replace(/^[-*]\s+/,"")}/></span></div>;if(/^\d+\.\s+/.test(line))return <div key={j} className="flex gap-2 pl-1"><span>{line.match(/^\d+/)?.[0]}.</span><span><Inline text={line.replace(/^\d+\.\s+/,"")}/></span></div>;return <p key={j}><Inline text={line}/></p>})}</div>})}</div>}
