"use client";

import { useEffect, useState } from "react";
import type { User } from "firebase/auth";
import { usePathname, useRouter } from "next/navigation";
import { LogOut, Mail, MoreHorizontal, PanelLeftClose, PanelLeftOpen, Pencil, Plug, Send, SquarePen, Trash2, UserCircle } from "lucide-react";
import { signOutCurrentUser } from "@/lib/auth/firebase-client";
import { EmailConnections } from "@/components/email-connections";
import { DelayedSkeleton, SidebarLoadingSkeleton } from "@/components/loading-skeleton";

const LOGO="https://res.cloudinary.com/dbqmhnahl/image/upload/v1787531960/file_00000000eed481f795676cc974695840_nh7jee.png";
type Chat={id:string;title:string;created_at?:string;updated_at?:string};
type Props={user:User;global?:boolean};
type ChatCreatedEvent=CustomEvent<{chat?:Chat}>;

export function WorkspaceSidebar({user,global=false}:Props){
 const router=useRouter();const pathname=usePathname();
 const [chats,setChats]=useState<Chat[]>([]),[loadingChats,setLoadingChats]=useState(global),[side,setSide]=useState(true),[mobileOpen,setMobileOpen]=useState(false),[profile,setProfile]=useState(false),[menu,setMenu]=useState<string|null>(null);
 useEffect(()=>{if(!global)return;let alive=true;const load=async()=>{try{const token=await user.getIdToken();const r=await fetch("/api/chats",{headers:{Authorization:`Bearer ${token}`},cache:"no-store"});if(!r.ok)return;const d=await r.json();if(alive){const serverChats=Array.isArray(d.chats)?d.chats:[];setChats(current=>{const pending=current.filter(c=>c.id.startsWith("pending-")&&!serverChats.some((s:Chat)=>s.title===c.title));return [...serverChats,...pending].sort((a,b)=>String(b.updated_at||b.created_at||"").localeCompare(String(a.updated_at||a.created_at||"")))})}}catch{}finally{if(alive)setLoadingChats(false)}};void load();return()=>{alive=false}},[user,global]);
 useEffect(()=>{if(!global)return;const open=()=>setMobileOpen(true);window.addEventListener("sanmine:open-sidebar",open);const onDocumentClick=(event:MouseEvent)=>{const target=event.target as HTMLElement|null;if(target?.closest('button[aria-label="Open sidebar"]'))setMobileOpen(true)};document.addEventListener("click",onDocumentClick);return()=>{window.removeEventListener("sanmine:open-sidebar",open);document.removeEventListener("click",onDocumentClick)}},[global]);
 useEffect(()=>{if(!global)return;const onChatCreated=(event:Event)=>{const chat=(event as ChatCreatedEvent).detail?.chat;if(!chat)return;setChats(xs=>{const withoutSame=xs.filter(c=>c.id!==chat.id&&!((chat.id.startsWith("pending-")||c.id.startsWith("pending-"))&&c.title===chat.title));return [chat,...withoutSame]});};window.addEventListener("sanmine:chat-created",onChatCreated);return()=>window.removeEventListener("sanmine:chat-created",onChatCreated)},[global]);
 useEffect(()=>{const handlePointerDown=(event:PointerEvent)=>{const target=event.target as HTMLElement|null;if(menu&&!target?.closest(`[data-chat-menu-root="${menu}"]`))setMenu(null);if(profile&&!target?.closest("[data-profile-menu-root]"))setProfile(false)};document.addEventListener("pointerdown",handlePointerDown);return()=>document.removeEventListener("pointerdown",handlePointerDown)},[menu,profile]);
 if(!global)return null;
 const fresh=()=>{setMenu(null);setProfile(false);setMobileOpen(false);router.push("/",{scroll:false});};
 const openChat=(id:string)=>{if(id.startsWith("pending-"))return;setMenu(null);setMobileOpen(false);router.push(`/chat/${id}`,{scroll:false});};
 const remove=async(id:string)=>{if(!window.confirm("Delete this chat?"))return;try{const token=await user.getIdToken();const r=await fetch(`/api/chats/${id}`,{method:"DELETE",headers:{Authorization:`Bearer ${token}`}});if(!r.ok){const data=await r.json().catch(()=>null);throw new Error(data?.error||"Unable to delete chat.");}setChats(xs=>xs.filter(c=>c.id!==id));if(pathname===`/chat/${id}`)fresh()}catch(error){console.error("Delete chat failed",error);window.alert(error instanceof Error?error.message:"Unable to delete chat.")}setMenu(null)};
 const name=user.displayName||user.email?.split("@")[0]||"User";
 return <><div className={`fixed inset-0 z-30 bg-black/20 transition-opacity md:hidden ${mobileOpen?"opacity-100":"pointer-events-none opacity-0"}`} onClick={()=>setMobileOpen(false)}/><aside data-sanmine-workspace-sidebar className={`${mobileOpen?"flex":"hidden"} fixed inset-y-0 left-0 z-40 w-[78vw] max-w-[310px] shrink-0 flex-col overflow-y-auto overscroll-contain border-r border-[var(--line)] bg-[#FBFBF9] p-3 shadow-xl md:sticky md:top-0 md:flex md:h-screen md:max-h-screen md:shadow-none ${side?"md:w-[270px]":"md:w-[72px]"}`}>
  <div className={`sticky top-0 z-20 flex shrink-0 items-center bg-[#FBFBF9] pb-5 pt-1 ${side?"justify-between px-2":"justify-center"}`}>{side?<button onClick={fresh} className="flex items-center gap-2.5"><img src={LOGO} alt="Sanmine Space" className="h-7 w-7 rounded-md object-cover"/><span className="text-[15px] font-semibold">Sanmine Space</span></button>:null}<button onClick={()=>setSide(v=>!v)} className="grid h-8 w-8 shrink-0 place-items-center rounded-lg text-[#5f5b54] hover:bg-black/5" aria-label={side?"Collapse sidebar":"Expand sidebar"}>{side?<PanelLeftClose size={18}/>:<PanelLeftOpen size={18}/>}</button></div>
  <div className="shrink-0 space-y-1"><button onClick={fresh} className={`flex w-full items-center rounded-lg py-2.5 text-sm font-medium hover:bg-black/5 ${side?"gap-2 px-3":"justify-center"}`} aria-label="New chat"><SquarePen size={17}/>{side&&"New chat"}</button><button onClick={()=>{setMobileOpen(false);router.push("/plugins")}} className={`flex w-full items-center rounded-lg py-2.5 text-sm font-medium hover:bg-black/5 ${pathname==="/plugins"?"bg-black/5":""} ${side?"gap-2 px-3":"justify-center"}`} aria-label="Plugins"><Plug size={17}/>{side&&"Plugins"}</button><button onClick={()=>{setMobileOpen(false);router.push("/campaigns")}} className={`flex w-full items-center rounded-lg py-2.5 text-sm font-medium hover:bg-black/5 ${pathname==="/campaigns"?"bg-black/5":""} ${side?"gap-2 px-3":"justify-center"}`} aria-label="Campaigns"><Send size={17}/>{side&&"Campaigns"}</button><button onClick={()=>{setMobileOpen(false);router.push("/emails")}} className={`flex w-full items-center rounded-lg py-2.5 text-sm font-medium hover:bg-black/5 ${pathname==="/emails"?"bg-black/5":""} ${side?"gap-2 px-3":"justify-center"}`} aria-label="Emails"><Mail size={17}/>{side&&"Emails"}</button></div>
  {side&&<div className="mt-7 min-h-0 flex-1"><div className="px-3 text-[11px] font-semibold uppercase tracking-[.13em] text-[#99958c]">Recent</div>{loadingChats?<DelayedSkeleton><SidebarLoadingSkeleton/></DelayedSkeleton>:<div className="mt-2 space-y-0.5">{chats.map(c=><div key={c.id} data-chat-menu-root={c.id} className="group relative flex rounded-lg hover:bg-black/5"><button onClick={()=>openChat(c.id)} disabled={c.id.startsWith("pending-")} className="min-w-0 flex-1 truncate px-3 py-2 text-left text-[13px] disabled:cursor-default">{c.title||"New chat"}</button>{!c.id.startsWith("pending-")&&<button onClick={()=>setMenu(menu===c.id?null:c.id)} className="mr-1 grid h-7 w-7 shrink-0 place-items-center self-center rounded-md text-[#77736b] hover:bg-black/10" aria-label="Chat options"><MoreHorizontal size={17}/></button>}{menu===c.id&&<div className="absolute right-1 top-9 z-50 w-40 rounded-xl border border-[#e3dfd7] bg-white p-1.5 shadow-xl"><button onClick={()=>setMenu(null)} className="flex w-full gap-2 rounded-lg px-2.5 py-2 text-sm hover:bg-black/5"><Pencil size={14}/>Rename</button><button onClick={()=>void remove(c.id)} className="flex w-full gap-2 rounded-lg px-2.5 py-2 text-sm text-[#9a5549] hover:bg-[#fff5f2]"><Trash2 size={14}/>Delete</button></div>}</div>)}{!chats.length&&<div className="px-3 py-2 text-xs text-[#aaa69d]">No recent chats yet.</div>}</div>}</div>}
  <div className="sticky bottom-0 z-20 relative mt-auto shrink-0 border-t border-[var(--line)] bg-[#FBFBF9] pt-3"><div data-profile-menu-root>{profile&&<div className="absolute bottom-[calc(100%+10px)] left-0 right-0 z-50 rounded-xl border bg-white p-2 shadow-xl"><div className="flex gap-3 px-2 py-2">{user.photoURL?<img src={user.photoURL} alt="" className="h-8 w-8 shrink-0 rounded-full object-cover"/>:<div className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-[#e4e1d9]"><UserCircle size={19}/></div>}<div className="min-w-0"><div className="truncate text-sm font-semibold">{name}</div><div className="truncate text-xs text-[#858178]">{user.email}</div></div></div><EmailConnections user={user}/><button onClick={async()=>{setProfile(false);await signOutCurrentUser()}} className="mt-1 flex w-full gap-2 rounded-lg px-2.5 py-2 text-sm"><LogOut size={15}/>Log out</button></div>}<button onClick={()=>setProfile(v=>!v)} className={`flex w-full items-center rounded-xl py-2.5 ${side?"gap-3 px-2":"justify-center"}`}>{user.photoURL?<img src={user.photoURL} alt="" className="h-8 w-8 shrink-0 rounded-full object-cover"/>:<div className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-[#e4e1d9]"><UserCircle size={19}/></div>}{side&&<div className="min-w-0 text-left"><div className="truncate text-[13px] font-medium">{name}</div><div className="truncate text-[11px] text-[#949087]">{user.email}</div></div>}</button></div></div>
 </aside></>;
}
