import { NextResponse } from "next/server";
import { getRequestUser } from "@/lib/auth/request-user";
import { sql } from "@/lib/db/neon";
import { runProductionMigrations } from "@/lib/db/migrations";
import { AppError, errorResponse, errorStatus } from "@/lib/api/errors";
import { enforceRateLimit } from "@/lib/api/rate-limit";
import { z } from "zod";
const Body=z.object({leadId:z.string().uuid(),stage:z.enum(["new","qualified","contacted","replied","meeting","proposal","won","lost"]),notes:z.string().max(10000).optional(),nextActionAt:z.string().datetime().nullable().optional()});
export async function GET(request:Request){try{const user=await getRequestUser(request);await runProductionMigrations();await enforceRateLimit(`crm:get:${user.uid}`,60,60_000);const rows=await sql`SELECT d.*,l.name,l.email,l.website_url,l.lead_score,l.niche,l.country FROM crm_deals d JOIN leads l ON l.id=d.lead_id WHERE d.user_id=${user.uid} ORDER BY d.updated_at DESC`;return NextResponse.json({deals:rows});}catch(error){return NextResponse.json(errorResponse(error,"Unable to load CRM pipeline."),{status:errorStatus(error)});}}
export async function PATCH(request:Request){try{const user=await getRequestUser(request);await runProductionMigrations();await enforceRateLimit(`crm:write:${user.uid}`,60,60_000);const parsed=Body.safeParse(await request.json().catch(()=>null));if(!parsed.success)throw new AppError("VALIDATION_ERROR","Invalid CRM update.",400);const {leadId,stage,notes,nextActionAt}=parsed.data;const lead=await sql`SELECT id FROM leads WHERE id=${leadId} AND user_id=${user.uid} LIMIT 1`;if(!lead[0])throw new AppError("NOT_FOUND","Lead not found.",404);const rows=await sql`INSERT INTO crm_deals(user_id,lead_id,stage,notes,next_action_at) VALUES(${user.uid},${leadId},${stage},${notes||""},${nextActionAt||null}) ON CONFLICT(user_id,lead_id) DO UPDATE SET stage=EXCLUDED.stage,notes=EXCLUDED.notes,next_action_at=EXCLUDED.next_action_at,updated_at=NOW() RETURNING *`;return NextResponse.json({deal:rows[0]});}catch(error){return NextResponse.json(errorResponse(error,"Unable to update CRM pipeline."),{status:errorStatus(error)});}}
