import { getAccessToken } from "@/lib/plugins/oauth";
import type { AgentTool } from "@/lib/agent/tools/types";
import { ensureProductionSchema } from "@/lib/agent/production";
import { sql } from "@/lib/db/neon";

const text = (v: unknown) => typeof v === "string" ? v.trim() : "";
const required = (v: unknown, name: string) => { const value = text(v); if (!value) throw new Error(`${name} is required.`); return value; };

async function api(url: string, init: RequestInit = {}) {
  const r = await fetch(url, { ...init, cache: "no-store", headers: { Accept: "application/json", ...(init.headers || {}) } });
  const data = await r.json().catch(() => ({}));
  if (!r.ok) throw new Error(String(data.message || data.error || `Provider request failed (${r.status}).`));
  return data as Record<string, any>;
}

async function github(uid: string, path: string, init?: RequestInit) {
  const token = await getAccessToken(uid, "github");
  return api(`https://api.github.com${path}`, { ...init, headers: { Authorization: `Bearer ${token}`, Accept: "application/vnd.github+json", "X-GitHub-Api-Version": "2022-11-28", ...(init?.headers || {}) } });
}

export const githubWorkspaceTool: AgentTool = {
  name: "github_workspace",
  description: "Read and modify the user's authorized GitHub repositories. Use action list_repos, read_file, write_file, create_file, or push_commit. write_file/create_file commit the content to the selected branch; this is the persistent save/push operation. Never invent repository contents or overwrite a file unless the user requested the change.",
  parameters: { type: "object", properties: {
    user_id: { type: "string" }, action: { type: "string", enum: ["list_repos","read_file","write_file","create_file","push_commit"] }, owner: { type: "string" }, repo: { type: "string" }, path: { type: "string" }, content: { type: "string" }, message: { type: "string" }, branch: { type: "string" }
  }, required: ["user_id","action"] },
  execute: async (args) => {
    const uid = required(args.user_id, "user_id"); const action = required(args.action, "action");
    if (action === "list_repos") { const data = await github(uid, "/user/repos?per_page=100&sort=updated"); return { status: "success", repositories: Array.isArray(data) ? data.map((r:any)=>({name:r.name,full_name:r.full_name,private:r.private,default_branch:r.default_branch})) : data }; }
    const owner = required(args.owner, "owner"); const repo = required(args.repo, "repo"); const path = required(args.path, "path"); const branch = text(args.branch);
    if (action === "read_file") { const data = await github(uid, `/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}/contents/${path.split("/").map(encodeURIComponent).join("/")}${branch ? `?ref=${encodeURIComponent(branch)}` : ""}`); if (Array.isArray(data)) return { status:"success", files:data.map((x:any)=>({name:x.name,path:x.path,type:x.type,sha:x.sha,size:x.size})) }; const content = data.encoding === "base64" ? Buffer.from(String(data.content||"").replace(/\n/g,""),"base64").toString("utf8") : String(data.content||""); return { status:"success", path:data.path, sha:data.sha, content }; }
    const content = required(args.content, "content"); const message = required(args.message, "message");
    let sha = ""; try { const existing = await github(uid, `/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}/contents/${path.split("/").map(encodeURIComponent).join("/")}${branch ? `?ref=${encodeURIComponent(branch)}` : ""}`); if (!Array.isArray(existing)) sha = String(existing.sha||""); } catch { /* create */ }
    if (action === "create_file" && sha) throw new Error("File already exists; use write_file to update it.");
    if (action !== "create_file" && action !== "write_file" && action !== "push_commit") throw new Error("Unsupported GitHub action.");
    const body: Record<string,unknown> = { message, content: Buffer.from(content,"utf8").toString("base64") }; if (sha) body.sha = sha; if (branch) body.branch = branch;
    const result = await github(uid, `/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}/contents/${path.split("/").map(encodeURIComponent).join("/")}`, { method:"PUT", headers:{"Content-Type":"application/json"}, body:JSON.stringify(body) });
    return { status:"success", saved:true, pushed:true, commit_sha:result.commit?.sha||null, path:result.content?.path||path };
  },
};

async function google(uid:string, url:string, init:RequestInit={}) { const token=await getAccessToken(uid,"google-workspace"); return api(url,{...init,headers:{Authorization:`Bearer ${token}`,...(init.headers||{})}}); }

export const googleDriveTool: AgentTool = {
  name:"google_drive", description:"Read, create, update and save files in the user's authorized Google Drive.", parameters:{type:"object",properties:{user_id:{type:"string"},action:{type:"string",enum:["list","read","create","update"]},file_id:{type:"string"},name:{type:"string"},content:{type:"string"},mime_type:{type:"string"},query:{type:"string"}},required:["user_id","action"]},
  execute:async(args)=>{const uid=required(args.user_id,"user_id");const action=required(args.action,"action");if(action==="list"){const q=text(args.query);const url=`https://www.googleapis.com/drive/v3/files?fields=files(id,name,mimeType,modifiedTime,webViewLink)&pageSize=100${q?`&q=${encodeURIComponent(q)}`:""}`;return {status:"success",files:(await google(uid,url)).files||[]};}if(action==="read"){const id=required(args.file_id,"file_id");const meta=await google(uid,`https://www.googleapis.com/drive/v3/files/${encodeURIComponent(id)}?fields=id,name,mimeType,size,modifiedTime`);if(meta.mimeType?.includes("google-apps")){return {status:"success",file:meta,note:"Google-native files should be read through the matching Docs, Sheets or Calendar tool."};}const token=await getAccessToken(uid,"google-workspace");const r=await fetch(`https://www.googleapis.com/drive/v3/files/${encodeURIComponent(id)}?alt=media`,{headers:{Authorization:`Bearer ${token}`},cache:"no-store"});if(!r.ok)throw new Error(`Drive download failed (${r.status}).`);return {status:"success",file:meta,content:await r.text()};}const name=required(args.name,"name");const content=text(args.content);const mime=text(args.mime_type)||"text/plain";if(action==="create"){const token=await getAccessToken(uid,"google-workspace");const form=new FormData();form.append("metadata",new Blob([JSON.stringify({name,mimeType:mime})],{type:"application/json"}));form.append("file",new Blob([content],{type:mime}),name);const r=await fetch("https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id,name,mimeType,webViewLink",{method:"POST",headers:{Authorization:`Bearer ${token}`},body:form,cache:"no-store"});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(String(data.error?.message||"Drive create failed."));return {status:"success",saved:true,file:data};}const id=required(args.file_id,"file_id");const token=await getAccessToken(uid,"google-workspace");const r=await fetch(`https://www.googleapis.com/upload/drive/v3/files/${encodeURIComponent(id)}?uploadType=media`,{method:"PATCH",headers:{Authorization:`Bearer ${token}`,"Content-Type":mime},body:content,cache:"no-store"});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(String(data.error?.message||"Drive update failed."));return {status:"success",saved:true,file:data};}
};

export const googleDocsTool: AgentTool = {
 name:"google_docs",description:"Read, create and update Google Docs in the user's authorized account.",parameters:{type:"object",properties:{user_id:{type:"string"},action:{type:"string",enum:["read","create","update"]},document_id:{type:"string"},title:{type:"string"},content:{type:"string"}},required:["user_id","action"]},
 execute:async(args)=>{const uid=required(args.user_id,"user_id");const action=required(args.action,"action");if(action==="read"){const id=required(args.document_id,"document_id");return {status:"success",document:await google(uid,`https://docs.googleapis.com/v1/documents/${encodeURIComponent(id)}`)};}if(action==="create"){const title=required(args.title,"title");const doc=await google(uid,"https://docs.googleapis.com/v1/documents",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title})});const content=text(args.content);if(content) await google(uid,`https://docs.googleapis.com/v1/documents/${doc.documentId}:batchUpdate`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({requests:[{insertText:{location:{index:1},text:content}}]})});return {status:"success",saved:true,document_id:doc.documentId,title:doc.title};}const id=required(args.document_id,"document_id");const content=required(args.content,"content");const doc=await google(uid,`https://docs.googleapis.com/v1/documents/${encodeURIComponent(id)}`);const end=doc.body?.content?.[doc.body.content.length-1]?.endIndex||1;return {status:"success",saved:true,document:await google(uid,`https://docs.googleapis.com/v1/documents/${encodeURIComponent(id)}:batchUpdate`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({requests:[{insertText:{location:{index:Math.max(1,end-1)},text:content}}]})})};}
};

export const googleSheetsTool: AgentTool = {
 name:"google_sheets",description:"Read and update Google Sheets in the user's authorized account.",parameters:{type:"object",properties:{user_id:{type:"string"},action:{type:"string",enum:["read","write"]},spreadsheet_id:{type:"string"},range:{type:"string"},values:{type:"array"}},required:["user_id","action"]},
 execute:async(args)=>{const uid=required(args.user_id,"user_id");const id=required(args.spreadsheet_id,"spreadsheet_id");const range=required(args.range,"range");if(args.action==="read")return {status:"success",data:await google(uid,`https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(id)}/values/${encodeURIComponent(range)}`)};const values=Array.isArray(args.values)?args.values:[];return {status:"success",saved:true,data:await google(uid,`https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(id)}/values/${encodeURIComponent(range)}?valueInputOption=USER_ENTERED`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({range,majorDimension:"ROWS",values})})};}
};

export const googleCalendarTool: AgentTool = {
 name:"google_calendar",description:"Read and create/update/delete events in the user's authorized Google Calendar.",parameters:{type:"object",properties:{user_id:{type:"string"},action:{type:"string",enum:["list","create","update","delete"]},event_id:{type:"string"},calendar_id:{type:"string"},summary:{type:"string"},description:{type:"string"},start:{type:"string"},end:{type:"string"}},required:["user_id","action"]},
 execute:async(args)=>{const uid=required(args.user_id,"user_id");const action=required(args.action,"action");const cal=text(args.calendar_id)||"primary";if(action==="list")return {status:"success",events:(await google(uid,`https://www.googleapis.com/calendar/v3/calendars/${encodeURIComponent(cal)}/events?maxResults=100&orderBy=startTime&singleEvents=true`)).items||[]};const id=text(args.event_id);if(action==="delete"){if(!id)throw new Error("event_id is required.");await google(uid,`https://www.googleapis.com/calendar/v3/calendars/${encodeURIComponent(cal)}/events/${encodeURIComponent(id)}`,{method:"DELETE"});return {status:"success",deleted:true,event_id:id};}const body={summary:required(args.summary,"summary"),description:text(args.description),start:{dateTime:required(args.start,"start")},end:{dateTime:required(args.end,"end")}};const url=`https://www.googleapis.com/calendar/v3/calendars/${encodeURIComponent(cal)}/events${id?`/${encodeURIComponent(id)}`:""}`;return {status:"success",saved:true,event:await google(uid,url,{method:id?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)})};}
};

export const notionTool: AgentTool = {
 name:"notion",description:"Read, search, create and update pages in the user's authorized Notion workspace.",parameters:{type:"object",properties:{user_id:{type:"string"},action:{type:"string",enum:["search","read","create","update"]},query:{type:"string"},page_id:{type:"string"},parent_id:{type:"string"},title:{type:"string"},content:{type:"string"}},required:["user_id","action"]},
 execute:async(args)=>{const uid=required(args.user_id,"user_id");const token=await getAccessToken(uid,"notion");const headers={Authorization:`Bearer ${token}`,"Notion-Version":"2026-03-11","Content-Type":"application/json"};const action=required(args.action,"action");if(action==="search")return {status:"success",results:await api("https://api.notion.com/v1/search",{method:"POST",headers,body:JSON.stringify({query:text(args.query)})})};const id=required(args.page_id,"page_id");if(action==="read")return {status:"success",page:await api(`https://api.notion.com/v1/pages/${encodeURIComponent(id)}`,{headers}),blocks:await api(`https://api.notion.com/v1/blocks/${encodeURIComponent(id)}/children`,{headers})};if(action==="update"){const content=text(args.content);if(!content)return {status:"error",message:"content is required."};return {status:"success",saved:true,blocks:await api(`https://api.notion.com/v1/blocks/${encodeURIComponent(id)}/children`,{method:"PATCH",headers,body:JSON.stringify({children:[{object:"block",type:"paragraph",paragraph:{rich_text:[{type:"text",text:{content}}]}}]})})};}const parent_id=required(args.parent_id,"parent_id");const title=required(args.title,"title");const content=text(args.content);return {status:"success",saved:true,page:await api("https://api.notion.com/v1/pages",{method:"POST",headers,body:JSON.stringify({parent:{page_id:parent_id},properties:{title:{title:[{type:"text",text:{content:title}}]}},children:content?[{object:"block",type:"paragraph",paragraph:{rich_text:[{type:"text",text:{content}}]}}]:[]})})};}
};

export const rssNewsTool: AgentTool = { name:"rss_news",description:"Read public RSS/Atom feeds. This is read-only; it does not write to publisher feeds.",parameters:{type:"object",properties:{url:{type:"string"},limit:{type:"number"}},required:["url"]},execute:async(args)=>{const url=required(args.url,"url");const u=new URL(url);if(!["http:","https:"].includes(u.protocol))throw new Error("Only http/https RSS URLs are allowed.");const r=await fetch(u,{cache:"no-store",headers:{Accept:"application/rss+xml, application/atom+xml, application/xml, text/xml"}});if(!r.ok)throw new Error(`RSS request failed (${r.status}).`);const xml=await r.text();const items=[...xml.matchAll(/<item[\s\S]*?<\/item>/gi)].slice(0,Math.min(Number(args.limit)||20,50)).map(m=>{const block=m[0];return {title:(block.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1]||"").replace(/<!\[CDATA\[|\]\]>/g,"").trim(),link:(block.match(/<link[^>]*>([\s\S]*?)<\/link>/i)?.[1]||"").trim(),published:(block.match(/<pubDate[^>]*>([\s\S]*?)<\/pubDate>/i)?.[1]||"").trim()};});return {status:"success",url,items};}};

export const scheduleGmailTool: AgentTool = { name:"schedule_gmail",description:"Schedule a Gmail email for the authenticated user. Requires an exact recipient, subject, body and future ISO timestamp. The existing campaign worker sends due scheduled approvals. Never schedule from an email-address lookup alone; the user must explicitly request sending/scheduling.",parameters:{type:"object",properties:{user_id:{type:"string"},user_email:{type:"string"},to:{type:"string"},subject:{type:"string"},body:{type:"string"},scheduled_at:{type:"string"}},required:["user_id","to","subject","body","scheduled_at"]},execute:async(args)=>{const userId=required(args.user_id,"user_id");const to=required(args.to,"to").toLowerCase();if(!/^\S+@\S+\.\S+$/.test(to))throw new Error("A valid recipient email is required.");const scheduledAt=new Date(required(args.scheduled_at,"scheduled_at"));if(Number.isNaN(scheduledAt.getTime())||scheduledAt.getTime()<=Date.now())throw new Error("scheduled_at must be a valid future timestamp.");await ensureProductionSchema();const connections=await sql`SELECT id FROM email_connections WHERE user_id=${userId} AND provider='google' ORDER BY updated_at DESC LIMIT 1`;if(!connections[0])return {status:"needs_connection",message:"Connect Gmail before scheduling an email."};const subject=required(args.subject,"subject"),body=required(args.body,"body");const rows=await sql`INSERT INTO email_approvals(user_id,connection_id,recipient,subject,body,status,scheduled_at,approved_at,idempotency_key) VALUES(${userId},${connections[0].id},${to},${subject},${body},'approved',${scheduledAt.toISOString()},NOW(),md5(${userId}||':'||${to}||':'||${scheduledAt.toISOString()}||':'||${subject})) RETURNING id,recipient,subject,scheduled_at,status`;return {status:"scheduled",scheduled:true,email:rows[0]};}};

export const workspaceIntegrationTools: AgentTool[] = [githubWorkspaceTool,googleDriveTool,googleDocsTool,googleSheetsTool,googleCalendarTool,notionTool,rssNewsTool,scheduleGmailTool];
