"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowLeft, Check, Clock3, Mail, Pause, Play, Plus, Send, Trash2, X } from "lucide-react";
import { useAuthUser } from "@/components/auth-gate";

type Connection={id:string;provider:"google"|"microsoft";email:string;display_name?:string|null};
type Campaign={id:string;name:string,status:string,subject:string,start_at:string,interval_minutes:number,total:number,sent:number,pending:number,failed:number};
type Approval={id:string,recipient:string,subject:string,body:string,status:string,scheduled_at:string|null,sender_email:string,campaign_name?:string|null,error?:string|null};

export default function CampaignsPage(){
  const user=useAuthUser();
  const [connections,setConnections]=useState<Connection[]>([]); const [campaigns,setCampaigns]=useState<Campaign[]>([]); const [approvals,setApprovals]=useState<Approval[]>([]);
  const [open,setOpen]=useState(false); const [busy,setBusy]=useState(""); const [error,setError]=useState("");
  const [form,setForm]=useState({name:"",connectionId:"",subject:"",body:"",recipients:"",startAt:"",intervalMinutes:"60"});
  const gmail=useMemo(()=>connections.filter(x=>x.provider==="google"),[connections]);
  const token=async()=>user?.getIdToken();
  const load=async()=>{if(!user)return;try{const t=await token();const [cr,rr]=await Promise.all([fetch("/api/campaigns",{headers:{Authorization:`Bearer ${t}`},cache:"no-store"}),fetch("/api/email/connections",{headers:{Authorization:`Bearer ${t}`},cache:"no-store"})]);const cd=await cr.json(),rd=await rr.json();if(!cr.ok)throw new Error(cd.error||"Unable to load campaigns.");if(!rr.ok)throw new Error(rd.error||"Unable to load email connections.");setCampaigns(cd.campaigns||[]);setApprovals(cd.approvals||[]);setConnections(rd.connections||[]);if(!form.connectionId&&rd.connections?.find((x:Connection)=>x.provider==="google"))setForm(f=>({...f,connectionId:rd.connections.find((x:Connection)=>x.provider==="google")?.id||""}));}catch(e){setError(e instanceof Error?e.message:"Unable to load campaigns.")}};
  useEffect(()=>{void load()},[user?.uid]);
  const create=async()=>{if(!user)return;setBusy("create");setError("");try{const t=await token();const recipients=form.recipients.split(/[\n,]+/).map(x=>x.trim().toLowerCase()).filter(Boolean);const r=await fetch("/api/campaigns",{method:"POST",headers:{Authorization:`Bearer ${t}`,"Content-Type":"application/json"},body:JSON.stringify({...form,intervalMinutes:Number(form.intervalMinutes),recipients})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to create campaign.");setOpen(false);setForm(f=>({...f,name:"",subject:"",body:"",recipients:"",startAt:"",intervalMinutes:"60"}));await load()}catch(e){setError(e instanceof Error?e.message:"Unable to create campaign.")}finally{setBusy("")}};
  const action=async(path:string,body:unknown,button:string)=>{if(!user)return;setBusy(button);setError("");try{const t=await token();const r=await fetch(path,{method:"PATCH",headers:{Authorization:`Bearer ${t}`,"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error||"Action failed.");await load()}catch(e){setError(e instanceof Error?e.message:"Action failed.")}finally{setBusy("")}};
  const remove=async(id:string)=>{if(!user||!confirm("Delete this campaign and its pending approvals?"))return;setBusy(id);try{const t=await token();const r=await fetch(`/api/campaigns/${id}`,{method:"DELETE",headers:{Authorization:`Bearer ${t}`}});const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to delete campaign.");await load()}catch(e){setError(e instanceof Error?e.message:"Unable to delete campaign.")}finally{setBusy("")}};
  const approvalAction=async(id:string,actionName:"approve"|"reject"|"send")=>{if(!user)return;setBusy(id+actionName);setError("");try{const t=await token();const r=await fetch(`/api/approvals/${id}`,{method:"PATCH",headers:{Authorization:`Bearer ${t}`,"Content-Type":"application/json"},body:JSON.stringify({action:actionName})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to update approval.");await load()}catch(e){setError(e instanceof Error?e.message:"Unable to update approval.")}finally{setBusy("")}};
  if(!user)return null;
  return <main className="min-h-screen bg-[var(--bg)] px-4 py-6 sm:px-8"><div className="mx-auto max-w-5xl">
    <div className="mb-8 flex items-center justify-between"><Link href="/" className="flex items-center gap-2 rounded-lg px-2 py-2 text-sm text-[#625e56] hover:bg-black/5"><ArrowLeft size={17}/>Back to chat</Link><button onClick={()=>setOpen(true)} className="flex items-center gap-2 rounded-xl bg-[#282721] px-4 py-2.5 text-sm font-medium text-white hover:opacity-90"><Plus size={16}/>New campaign</button></div>
    <div className="mb-8"><p className="mb-2 text-xs font-semibold uppercase tracking-[.12em] text-[#969188]">Phase 8 · Phase 9</p><h1 className="text-3xl font-semibold tracking-tight text-[#282721]">Approvals & campaigns</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[#77736a]">Review every outreach email before it can send. Approved campaign emails are delivered automatically when their scheduled time arrives.</p></div>
    {error&&<div className="mb-5 rounded-xl border border-[#ead6cf] bg-[#fff7f3] px-4 py-3 text-sm text-[#8b5145]">{error}</div>}
    <section className="mb-10"><div className="mb-3 flex items-center gap-2 text-sm font-semibold text-[#38362f]"><Mail size={16}/>Pending approval</div><div className="divide-y divide-[#e8e4dc] rounded-2xl border border-[#dedbd4] bg-[#fbfaf7]">{approvals.filter(a=>a.status==='pending'||a.status==='approved'||a.status==='failed').length===0?<div className="px-5 py-8 text-sm text-[#8b877e]">No emails waiting for approval.</div>:approvals.filter(a=>a.status==='pending'||a.status==='approved'||a.status==='failed').map(a=><div key={a.id} className="p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="text-sm font-semibold text-[#282721]">{a.recipient}</span><span className="rounded-full bg-[#efede7] px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wide text-[#77736a]">{a.status}</span>{a.campaign_name&&<span className="text-xs text-[#969188]">{a.campaign_name}</span>}</div><div className="mt-1 text-sm font-medium text-[#4b4840]">{a.subject}</div><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-[#6f6b63]">{a.body}</p>{a.error&&<p className="mt-2 text-xs text-[#9b5c50]">{a.error}</p>}</div><div className="flex shrink-0 gap-2">{a.status==='pending'&&<><button onClick={()=>void approvalAction(a.id,"approve")} disabled={!!busy} className="grid h-9 w-9 place-items-center rounded-lg border border-[#d9d5cd] bg-white hover:bg-[#f2f0eb] disabled:opacity-40" title="Approve"><Check size={15}/></button><button onClick={()=>void approvalAction(a.id,"reject")} disabled={!!busy} className="grid h-9 w-9 place-items-center rounded-lg border border-[#d9d5cd] bg-white hover:bg-[#f2f0eb] disabled:opacity-40" title="Reject"><X size={15}/></button></>}{a.status==='approved'&&<button onClick={()=>void approvalAction(a.id,"send")} disabled={!!busy} className="flex items-center gap-2 rounded-lg bg-[#282721] px-3 py-2 text-xs font-medium text-white disabled:opacity-40"><Send size={13}/>Send now</button>}{a.status==='failed'&&<button onClick={()=>void approvalAction(a.id,"send")} disabled={!!busy} className="flex items-center gap-2 rounded-lg bg-[#282721] px-3 py-2 text-xs font-medium text-white disabled:opacity-40"><Send size={13}/>Retry</button>}</div></div></div>)}</div></section>
    <section><div className="mb-3 flex items-center gap-2 text-sm font-semibold text-[#38362f]"><Clock3 size={16}/>Campaigns</div><div className="divide-y divide-[#e8e4dc] rounded-2xl border border-[#dedbd4] bg-[#fbfaf7]">{campaigns.length===0?<div className="px-5 py-8 text-sm text-[#8b877e]">No campaigns yet. Create one after connecting Gmail in Plugins.</div>:campaigns.map(c=><div key={c.id} className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2"><h3 className="text-sm font-semibold text-[#282721]">{c.name}</h3><span className="rounded-full bg-[#efede7] px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wide text-[#77736a]">{c.status}</span></div><p className="mt-1 text-xs text-[#8b877e]">{c.sent}/{c.total} sent · {c.pending} pending · every {c.interval_minutes} min</p><p className="mt-1 text-xs text-[#969188]">Starts {new Date(c.start_at).toLocaleString()}</p></div><div className="flex gap-2">{(c.status==='draft'||c.status==='paused')&&<button onClick={()=>void action(`/api/campaigns/${c.id}`,{action:c.status==='draft'?'activate':'resume'},c.id+'a')} disabled={!!busy} className="grid h-9 w-9 place-items-center rounded-lg border border-[#d9d5cd] bg-white hover:bg-[#f2f0eb] disabled:opacity-40" title="Activate"><Play size={14}/></button>}{c.status==='active'&&<button onClick={()=>void action(`/api/campaigns/${c.id}`,{action:"pause"},c.id+'p')} disabled={!!busy} className="grid h-9 w-9 place-items-center rounded-lg border border-[#d9d5cd] bg-white hover:bg-[#f2f0eb] disabled:opacity-40" title="Pause"><Pause size={14}/></button>}<button onClick={()=>void remove(c.id)} disabled={!!busy} className="grid h-9 w-9 place-items-center rounded-lg border border-[#d9d5cd] bg-white hover:bg-[#f2f0eb] disabled:opacity-40" title="Delete"><Trash2 size={14}/></button></div></div>)}</div></section>
    {open&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/25 p-4"><div className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-2xl border border-[#dedbd4] bg-[#fbfaf7] p-5 shadow-xl sm:p-7"><div className="mb-5 flex items-center justify-between"><div><h2 className="text-lg font-semibold text-[#282721]">Create campaign</h2><p className="mt-1 text-xs text-[#8b877e]">All recipients start as pending approval.</p></div><button onClick={()=>setOpen(false)} className="grid h-8 w-8 place-items-center rounded-lg hover:bg-black/5"><X size={17}/></button></div><div className="grid gap-4"><Field label="Campaign name"><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Founder outreach"/></Field><Field label="Gmail account"><select value={form.connectionId} onChange={e=>setForm({...form,connectionId:e.target.value})}><option value="">Select Gmail</option>{gmail.map(c=><option key={c.id} value={c.id}>{c.email}</option>)}</select>{!gmail.length&&<p className="mt-1 text-xs text-[#9b5c50]">Connect Gmail first in Plugins.</p>}</Field><Field label="Subject"><input value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})} placeholder="A quick idea for your team"/></Field><Field label="Email body"><textarea rows={7} value={form.body} onChange={e=>setForm({...form,body:e.target.value})} placeholder="Write the approved outreach email here..."/></Field><Field label="Recipients"><textarea rows={5} value={form.recipients} onChange={e=>setForm({...form,recipients:e.target.value})} placeholder="one@example.com\ntwo@example.com"/><p className="mt-1 text-xs text-[#969188]">One email per line. Each becomes a separate approval.</p></Field><div className="grid gap-4 sm:grid-cols-3"><Field label="Start"><input type="datetime-local" value={form.startAt} onChange={e=>setForm({...form,startAt:e.target.value})}/></Field><Field label="Interval (minutes)"><input type="number" min="1" value={form.intervalMinutes} onChange={e=>setForm({...form,intervalMinutes:e.target.value})}/></Field><div className="flex items-end"><div className="w-full rounded-xl bg-[#efede7] px-3 py-2.5 text-xs leading-5 text-[#77736a]">Approve each email before the worker can send it.</div></div></div><button onClick={()=>void create()} disabled={!!busy||!gmail.length} className="mt-2 flex h-11 items-center justify-center gap-2 rounded-xl bg-[#282721] text-sm font-medium text-white disabled:opacity-40">{busy==='create'?"Creating…":"Create campaign"}</button></div></div></div>}
  </div></main>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="mb-1.5 block text-xs font-medium text-[#5f5b53]">{label}</span>{children}</label>}
